// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeSqvzAuc8KbZKlVLpZhuWAsaoM-G6sJw',
    appId: '1:1049869151410:web:6fdd5c5263b8f28c1d6dab',
    messagingSenderId: '1049869151410',
    projectId: 'flutter-projects-35945',
    authDomain: 'flutter-projects-35945.firebaseapp.com',
    storageBucket: 'flutter-projects-35945.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnzytVMV5-ioaoZC1zE1opwieRsBCIaY',
    appId: '1:1049869151410:android:982ae23d097122eb1d6dab',
    messagingSenderId: '1049869151410',
    projectId: 'flutter-projects-35945',
    storageBucket: 'flutter-projects-35945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6DhuF2z1FTm-a1kODtAKbVHx4TXJCTOQ',
    appId: '1:1049869151410:ios:fd37e57dd17d18ea1d6dab',
    messagingSenderId: '1049869151410',
    projectId: 'flutter-projects-35945',
    storageBucket: 'flutter-projects-35945.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6DhuF2z1FTm-a1kODtAKbVHx4TXJCTOQ',
    appId: '1:1049869151410:ios:fd37e57dd17d18ea1d6dab',
    messagingSenderId: '1049869151410',
    projectId: 'flutter-projects-35945',
    storageBucket: 'flutter-projects-35945.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );
}
